#
# Make defs common to both 850C and SW102
#


# The integer build number for this release, MUST BE INCREMENTED FOR EACH RELEASE SO BOOTLOADER WILL INSTALL
# it is not user visible, but we must ensure it is monotonically increasing
VERSION_NUM := 20

# This is the user visible string for the version
VERSION_STRING := 0.5.0-beta.8

CFLAGS += -DVERSION_STRING=\"$(VERSION_STRING)\"
