#
# Make defs common to both 850C and SW102
#


# The integer build number for this release, MUST BE INCREMENTED FOR EACH RELEASE SO BOOTLOADER WILL INSTALL
VERSION_NUM := 19

VERSION_STRING := 0.5.0-beta.3

CFLAGS += -DVERSION_STRING=\"$(VERSION_STRING)\"
